"""update location model

Revision ID: ef50147160bc
Revises: ade04350d47b
Create Date: 2025-11-05 13:27:59.749452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef50147160bc'
down_revision: Union[str, Sequence[str], None] = 'ade04350d47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('name', sa.String(), nullable=False))
    op.add_column('locations', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('locations_created_by_fkey'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'users', ['owner_id'], ['id'])
    op.drop_column('locations', 'title')
    op.drop_column('locations', 'created_by')
    op.drop_column('locations', 'status')
    op.drop_column('locations', 'created_at')
    op.drop_column('locations', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_created_by_fkey'), 'locations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('locations', 'owner_id')
    op.drop_column('locations', 'name')
    # ### end Alembic commands ###
